import { useEffect, useState } from "react";
import { useTripData } from "./TripDataContext";

const field="w-full rounded-lg border border-[var(--line)] bg-[var(--card)] px-3 py-2 text-sm";
const action="rounded-lg bg-[var(--ac)] px-3 py-2 text-sm font-bold text-white disabled:opacity-50";

export function TripManager(){
  const trip=useTripData(); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState("");
  const [confirmation,setConfirmation]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [inviteUrl,setInviteUrl]=useState("");
  async function run(work:()=>Promise<void>){setBusy(true);setMessage("");try{await work();}catch(error){setMessage(error instanceof Error?error.message:"Операция не выполнена");}finally{setBusy(false);}}
  return <div className="mb-5 flex flex-wrap items-center gap-2">
    <label className="sr-only" htmlFor="trip-selector">Поездка</label><select id="trip-selector" className={`${field} max-w-xs font-semibold`} value={trip.selectedTrip?.id??""} onChange={(e)=>trip.selectTrip(e.target.value)}>{trip.trips.map((item)=><option value={item.id} key={item.id}>{item.name} · {item.role==="owner"?"владелец":"просмотр"}</option>)}</select>
    <button className={action} onClick={()=>setOpen(true)}>Управление поездками</button>
    {open&&<div className="fixed inset-0 z-[20000] grid place-items-center bg-black/45 p-4" role="dialog" aria-modal="true" aria-label="Управление поездками" onMouseDown={(e)=>e.target===e.currentTarget&&setOpen(false)}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-[var(--card)] p-5 shadow-2xl">
      <div className="flex items-center justify-between"><h2 className="font-display text-2xl font-bold">Поездки и доступ</h2><button className="text-2xl" aria-label="Закрыть" onClick={()=>setOpen(false)}>×</button></div>
      <section className="mt-5"><h3 className="font-bold">Новая поездка</h3><form className="mt-2 flex gap-2" onSubmit={(e)=>{e.preventDefault();void run(async()=>{await trip.createTrip(name);setName("");setMessage("Поездка создана.");});}}><input className={field} value={name} maxLength={120} required placeholder="Название" onChange={(e)=>setName(e.target.value)}/><button className={action} disabled={busy||!name.trim()}>Создать</button></form></section>
      {trip.selectedTrip&&<><section className="mt-6 border-t border-[var(--line)] pt-4"><h3 className="font-bold">{trip.selectedTrip.name}</h3>{!trip.isReadOnly?<form className="mt-2 flex gap-2" onSubmit={(e)=>{e.preventDefault();void run(async()=>{await trip.renameTrip(name||trip.selectedTrip!.name);setName("");setMessage("Название обновлено.");});}}><input className={field} value={name} placeholder="Новое название" onChange={(e)=>setName(e.target.value)}/><button className={action} disabled={busy||!name.trim()}>Переименовать</button></form>:<p className="mt-1 text-sm text-[var(--muted)]">Доступ только для просмотра.</p>}</section>
      <section className="mt-6"><h3 className="font-bold">Участники</h3><ul className="mt-2 divide-y divide-[var(--line)]">{trip.members.map((member)=><li className="flex justify-between py-2 text-sm" key={member.userId}><span>{member.email}</span><strong>{member.role==="owner"?"владелец":"читатель"}</strong></li>)}</ul></section>
      {!trip.isReadOnly&&<><section className="mt-6"><h3 className="font-bold">Пригласить читателя</h3><form className="mt-2 flex gap-2" onSubmit={(e)=>{e.preventDefault();void run(async()=>{const created=await trip.createInvitation(email);const url=new URL(window.location.href);url.searchParams.set("invite",created.token);setInviteUrl(url.toString());setEmail("");});}}><input className={field} type="email" required value={email} placeholder="email@example.com" onChange={(e)=>setEmail(e.target.value)}/><button className={action} disabled={busy}>Пригласить</button></form>{inviteUrl&&<div className="mt-2 rounded-lg bg-[var(--soft)] p-3 text-sm"><p className="break-all">{inviteUrl}</p><button className="mt-2 font-bold text-[var(--ac)]" onClick={()=>void navigator.clipboard.writeText(inviteUrl)}>Копировать ссылку</button></div>}
      <ul className="mt-3 space-y-2">{trip.invitations.map((invite)=><li className="flex items-center justify-between gap-2 text-sm" key={invite.id}><span>{invite.email} · {invite.status}</span>{invite.status==="pending"&&<button className="font-bold text-[#a04432]" onClick={()=>void run(()=>trip.revokeInvitation(invite.id))}>Отозвать</button>}</li>)}</ul></section>
      <section className="mt-6 border-t border-[#d8a08d] pt-4"><h3 className="font-bold text-[#a04432]">Удалить поездку</h3><p className="mt-1 text-sm">Введите точное название: <strong>{trip.selectedTrip.name}</strong></p><div className="mt-2 flex gap-2"><input className={field} value={confirmation} onChange={(e)=>setConfirmation(e.target.value)}/><button className="rounded-lg bg-[#a04432] px-3 py-2 text-sm font-bold text-white disabled:opacity-50" disabled={busy||confirmation!==trip.selectedTrip.name} onClick={()=>void run(async()=>{await trip.deleteTrip(confirmation);setConfirmation("");setOpen(false);})}>Удалить</button></div></section></>}
      </>}{message&&<p className="mt-4 text-sm font-semibold" role="status">{message}</p>}
    </div></div>}
  </div>;
}

export function InvitationAcceptor(){const {acceptInvitation}=useTripData();const [message,setMessage]=useState("");
  useEffect(()=>{const token=new URLSearchParams(window.location.search).get("invite");if(!token)return;setMessage("Принимаем приглашение…");void acceptInvitation(token).then(()=>setMessage("Приглашение принято.")).catch((e:unknown)=>setMessage(e instanceof Error?e.message:"Не удалось принять приглашение")).finally(()=>{const url=new URL(window.location.href);url.searchParams.delete("invite");history.replaceState(null,"",url);});},[]);
  return message?<div className="fixed bottom-5 left-1/2 z-[25000] -translate-x-1/2 rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-bold text-[var(--card)]" role="status">{message}</div>:null;
}
