import { useState } from "react";
import { useTripData } from "../../trip/TripDataContext";
import { uid } from "../shared";

export function Notes() {
  const { data, updateData, isReadOnly } = useTripData();
  const [draft, setDraft] = useState({ title: "", url: "" });
  if (!data) return null;
  const guard = (action: () => void) => isReadOnly ? window.dispatchEvent(new CustomEvent("trip:readonly")) : action();
  const add = () => { if (!draft.title.trim() || !draft.url.trim()) return; guard(() => { updateData((current) => ({ ...current, links: [...current.links, { id: uid("link"), title: draft.title.trim(), url: draft.url.trim() }] })); setDraft({ title: "", url: "" }); }); };
  const inputStyle = { border: "1px solid var(--line,#e7dcc7)", borderRadius: 9, padding: "9px 12px", fontSize: 14, background: "var(--soft,#fdfaf3)" } as const;
  return <div className="notes-grid" style={{ animation: "fadeUp .4s ease both", display: "grid", gridTemplateColumns: "1.4fr 1fr", gap: 20 }}>
    <div style={{ background: "var(--card,#fff)", border: "1px solid var(--line,#e7dcc7)", borderRadius: 16, padding: "20px 22px" }}><div style={{ fontFamily: "'Playfair Display',serif", fontSize: 20, fontWeight: 600, marginBottom: 12 }}>Заметки</div><textarea value={data.notes} onChange={(event) => guard(() => updateData((current) => ({ ...current, notes: event.target.value })))} placeholder="важное, о собаках, документы, что не забыть…" style={{ width: "100%", minHeight: 320, border: "1px solid var(--line,#e7dcc7)", borderRadius: 12, padding: "14px 16px", fontSize: 15, lineHeight: 1.6, background: "var(--soft,#fdfaf3)", resize: "vertical" }} /></div>
    <div style={{ background: "var(--card,#fff)", border: "1px solid var(--line,#e7dcc7)", borderRadius: 16, padding: "20px 22px" }}><div style={{ fontFamily: "'Playfair Display',serif", fontSize: 20, fontWeight: 600, marginBottom: 12 }}>Полезные ссылки</div><div style={{ display: "flex", flexDirection: "column", gap: 8 }}>{data.links.map((link) => <div key={link.id} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 12px", border: "1px solid var(--line,#f0e5d1)", borderRadius: 10 }}><span style={{ width: 8, height: 8, borderRadius: "50%", background: "var(--ac2,#cf9440)", flex: "none" }} /><a href={link.url} target="_blank" rel="noreferrer" style={{ flex: 1, fontSize: 14, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{link.title}</a><button onClick={() => guard(() => updateData((current) => ({ ...current, links: current.links.filter((item) => item.id !== link.id) })))} style={{ border: "none", background: "none", color: "#c4b5a0", cursor: "pointer", fontSize: 16 }}>×</button></div>)}</div><div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 12 }}><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="название" style={inputStyle} /><div style={{ display: "flex", gap: 8 }}><input value={draft.url} onChange={(event) => setDraft({ ...draft, url: event.target.value })} placeholder="https://…" style={{ ...inputStyle, flex: 1 }} /><button onClick={add} style={{ border: "none", background: "var(--ac,#b95c3f)", color: "#fff", borderRadius: 9, padding: "0 16px", fontWeight: 600, fontSize: 14, cursor: "pointer" }}>+</button></div></div></div>
  </div>;
}
